version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "63:63"
    volumes:
      - /root/data/metube/downloads:/downloads