---
version: "2.1"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /root/data/Sabnzbd/data:/config
      - /root/data/Sabnzbd/downloads:/downloads #optional
      - /root/data/Sabnzbd/incomplete/downloads:/incomplete-downloads #optional
    ports:
      - 8140:8140
    restart: unless-stopped
